name: Update community.txt from upstream

on:
  schedule:
    - cron: "0 3 * * *"   # каждый день в 03:00 UTC
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download latest community.lst
        run: |
          curl -L "https://raw.githubusercontent.com/1andrevich/Re-filter-lists/main/community.lst" -o community.lst

      - name: Convert to community.txt
        run: |
          sed 's/\r$//' community.lst > community.txt

      - name: Commit and push if changed
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add community.txt
          git commit -m "Auto update community.txt" || exit 0
          git push